### ISSUE TITLE
filtering on dates "today", "yesterday" does not seem to work

### ISSUE THREAD

**Issue by pahles** [psidnell/ofexport2#9]
I'm trying to filter my completed tasks of today using `of2 -ti 'completion.is("today")'`. This results in no output, even if there are tasks marked completed today. The same for `of2 -ti 'completion.is("yesterday")'`. 

If I fill in a specific date like `of2 -ti 'completion.is("2015-03-19")'` it shows the tasks with a completion date of March 18... 

If I use `of2 -ti 'completion.between("Monday","today")'`, it will only output completed tasks from Monday to yesterday (including).

**Comment by psidnell** [comment]
That's pretty strange - I've just tried your example on my machine and it's fine - I'm guessing its some sort of time zone issue

- What time zone are you in?
- Does of2 display the correct completion date for the item in the output?

If it were displaying the wrong dates for items I'd guess there were a time zone related conversion problem reading the database data - otherwise it's very mysterious.

**Comment by pahles** [comment]
* I'm in Central European Time (UTC +1);
* of2 does show the correct completion date.

I'll try to investigate further.

**Comment by psidnell** [comment]
Since we changed to BST I've had some unit test failures - I've just issued a fix for those, it may relate to the issue you're having.

**Comment by pahles** [comment]
OK, had to reinstall because I got a new MBP. It seems to have been resolved. Issuing `of2 -ti 'completion.is("2015-03-19")'` now shows all tasks completed on March 19. Issuing `of2 -ti 'completion.is("today")'` shows tasks completed today. Not sure of course if this is because I reinstalled or because of your fix. I'll try on my old MBP later.

**Comment by pahles** [comment]
I won't be able to test this on my old MBP anymore and since it is working now I guess the problem was related to my specific setup. Closing the issue.
